### ISSUE TITLE
Error when trying to convert GP5 to MIDI

### ISSUE THREAD

**Issue by AdamSEY** [LibreScore/dl-librescore#16]
npx dl-librescore@latest -i /home/ubuntu/guitarpro-converter/temp/file_name.gp5 -o /home/ubuntu/guitarpro-converter/temp/dd.midi -t midi -v

```
ℹ File loaded
⠁ Processing…node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/ubuntu/.npm/_npx/47461c73a56e4a1f/node_modules/webmscore/webmscore.lib.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:230:25)
      at instantiateAsync (/home/ubuntu/.npm/_npx/47461c73a56e4a1f/node_modules/webmscore/webmscore.nodejs.cjs:60:53226)
      at createWasm (/home/ubuntu/.npm/_npx/47461c73a56e4a1f/node_modules/webmscore/webmscore.nodejs.cjs:60:53835)
      at /home/ubuntu/.npm/_npx/47461c73a56e4a1f/node_modules/webmscore/webmscore.nodejs.cjs:60:266911 {
    input: '/home/ubuntu/.npm/_npx/47461c73a56e4a1f/node_modules/webmscore/webmscore.lib.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
```

**Comment by sealsrock12** [comment]
We only support MSCZ files for conversion.

**Comment by Xmader** [comment]
I believe there's a separate problem.
 Reopened as https://github.com/LibreScore/webmscore/issues/10


> Node.js 18 [added a few browser-compatible APIs](https://nodejs.org/en/blog/announcements/v18-release-announce#new-globally-available-browser-compatible-apis), so [webmscore](https://github.com/LibreScore/webmscore) could no longer properly detect if it's running in a Node.js environment or browser environment.

**Comment by PeterNjeim** [comment]
Caused by: https://github.com/nodejs/undici/issues/1857#issuecomment-1793572098
