### ISSUE TITLE
i get this error 

### ISSUE THREAD

**Issue by fractured345** [LibreScore/dl-librescore#21]
TypeError: Cannot read properties of null (reading '1')
    at get imgType [as imgType] (C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:4355:58)
    at C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:30823:27
    at Generator.next (<anonymous>)
    at C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:16:12)
    at exportPDF (C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:30822:41)
    at C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:31316:50
    at Generator.next (<anonymous>)
    at C:\Users\badge\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71

Node.js v18.16.0

**Comment by aliciapaz** [comment]
Same error here when using the command line tool! :c 
I'm also using Node.js 18.16.0

**Comment by sealsrock12** [comment]
What are you trying to do?

**Comment by PeterNjeim** [comment]
Official scores can only be downloaded with the Userscript with a Pro+ subscription
