### ISSUE TITLE
CLI can't download PDF's of Official Scores

### ISSUE THREAD

**Issue by zcccccc1** [LibreScore/dl-librescore#35]
```
> npx dl-librescore@latest
? MuseScore URL or path to file or folder:
  (starts with https://musescore.com/ or is a path) right-click to paste
  https://musescore.com/user/39593079/scores/6950266
! ID: 6950266
  Title: Do You Hear The People Sing? - Les Miserables Musical, Susan Boyle (Piano Solo)
  Continue? Yes

? Filetype Selection midi, mp3, pdf
? Output Directory: %USERPROFILE%\Documents\musescore-downloads
⠁ Processing…%USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:4379
        const imgtype = thumbnail.match(/score_0\.(\w+)/)[1];
                                                         ^

TypeError: Cannot read properties of null (reading '1')
    at get imgType [as imgType] (%USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:4379:58)
    at %USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:30847:27
    at Generator.next (<anonymous>)
    at %USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (%USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:16:12)
    at exportPDF (%USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:30846:41)
    at %USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:31374:50
    at Generator.next (<anonymous>)
    at %USERPROFILE%\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71

Node.js v20.9.0
```

**Comment by PeterNjeim** [comment]
Official scores require a MuseScore Pro+ subscription, and thus only available with the Userscript, as the CLI doesn't have the option of entering account credentials.
