### ISSUE TITLE
(CLI) TypeError: Cannot read properties of null (reading 'url')

### ISSUE THREAD

**Issue by fenugrec** [LibreScore/dl-librescore#47]
```
$ dl-librescore -i https://musescore.com/classicman/scores/63256 -t midi -v
(node:371307) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

New version is available! Current version is 0.34.60
Run npm i -g dl-librescore@0.34.61 to update
! ID: 63256
  Title: Hungarian Rhapsody No. 2

⠂ Processing…/usr/lib/node_modules/dl-librescore/dist/cli.js:4699
    return info.url;
                ^

TypeError: Cannot read properties of null (reading 'url')
    at /usr/lib/node_modules/dl-librescore/dist/cli.js:4699:17
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/dl-librescore/dist/cli.js:17:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.5.0
```

I do see that  latest version is 0.34.61 but it doesn't look like recent commits would have fixed this ? Unable to test right now (Arch repos have 0.34.60 for now)

**Comment by PeterNjeim** [comment]
Command-line tool isn't working right now, see #44
