### ISSUE TITLE
CLI can't download PDF's of Official Scores

### ISSUE THREAD

**Issue by rajeevtapadia** [LibreScore/dl-librescore#72]
UPDATE:
This got automatically fixed. Seems like this only happens when there is the start free trial popup showing up. 
To solve:
1. Open the site in incognito and use the download button provided by the extension

To reproduce:
1. go to https://musescore.com/official_scores/scores/6976459 and press download option (tampermonkey)
also downloading midi and mp3 worker find with the tampermonkey script problem is only with pdf

I also tried the that cli tool for the same link. The error was
```
⠁ Processing…C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:5015
        const imgtype = thumbnail.match(/score_0\.(\w+)/)[1];
                                                         ^

TypeError: Cannot read properties of null (reading '1')
    at get imgType [as imgType] (C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:5015:58)
    at C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:31854:27
    at Generator.next (<anonymous>)
    at C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:16:12)
    at exportPDF (C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:31853:56)
    at C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:32381:50
    at Generator.next (<anonymous>)
    at C:\Users\user\AppData\Local\npm-cache\_npx\47461c73a56e4a1f\node_modules\dl-librescore\dist\cli.js:20:71

Node.js v20.4.0
```

**Comment by PeterNjeim** [comment]
Duplicate of #10
